= Arbeitspakete Dokumentation
Moritz Eichhorn
1.0.0, 2021-12-09
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// print the toc here (not at the default position)
//toc::

== Websockets
=== Allgemeines
Bei Websockets besteht zwischen dem Server und dem Client eine
bidirektionale Verbindung. So kann auch der Server dem Client
Informationen zukommenlassen.

Beispiele:

* Chat
* Live-Sport-Ticker
* Onlinespiele

=== Implementierung
* Extension einfügen:

[source]
----
./mvnw quarkus:add-extension -Dextensions="websockets"
----

* Neuen Serverendpoint Erstellen:

[source,java]
----
@ServerEndpoint("/chat/{username}")
@ApplicationScoped
public class ChatSocket {
}
----

* Zur Verwaltung der Sessions eine Map erstellen:

[source,java]
----
Map<String, Session> sessions = new ConcurrentHashMap<>();
----

* Methoden für den Umgang mit Websockets in `ChatSocket` einfügen:

[source,java]
----
@OnOpen
public void onOpen(Session session, @PathParam("username") String username) {
    sessions.put(username, session);
}

@OnClose
public void onClose(Session session, @PathParam("username") String username) {
    sessions.remove(username);
    broadcast("User " + username + " left");
}

@OnError
public void onError(Session session, @PathParam("username") String username, Throwable throwable) {
    sessions.remove(username);
    broadcast("User " + username + " left on error: " + throwable);
}

@OnMessage
public void onMessage(String message, @PathParam("username") String username) {
    if (message.equalsIgnoreCase("_ready_")) {
        broadcast("User " + username + " joined");
    } else {
        broadcast(">> " + username + ": " + message);
    }
}

private void broadcast(String message) {
    sessions.values().forEach(s -> {
        s.getAsyncRemote().sendObject(message, result ->  { <1>
            if (result.getException() != null) {
                System.out.println("Unable to send message: " + result.getException());
            }
        });
    });
}
----
<1> Using `getAsyncRemote().sendObject()` on a session you can send a message to the client




